title: Jacob MacLeod # your name (or website title) here
# your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly Skilled Software Developer with experience in designing and maintaining simulation programs written in C++. Bachelor of Science in Computer Engineeering, Wright State University. Previously employed as Junior Software Engineer with Clear Creek Applied Technologies.
  <br><br>
  I am interested in Software Engineering and Data Science and have been learning about Data Science through online classes
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-macleod-082897108/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
